name: Flutter Build & Upload Artifact

on:
  workflow_dispatch:


jobs:
  # build-abi:
  #   uses: ./.github/workflows/abi.yml

  build-apk:
    # needs: build-abi
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Flutter SDK
      uses: subosito/flutter-action@v2.16.0
      with:
        channel: stable
        cache: true

    - name: Download rust abi from artifact
      uses: actions/download-artifact@v4.1.7

    - name: Copy Abi
      run: |
        echo "Testing abi"
        ls ./android-abi-arm
        mv  ./android-abi-arm ./android/app/src/main/jniLibs
    
    - name: Set up rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    
    # - name: Set up flutter rust bridge
    #   run: cargo install 'flutter_rust_bridge_codegen@^2.0.0-dev.0'

    - name: Build Prepare
      run: |
        flutter pub get
        chmod +x ./rust_builder

    - name: Build APK
      run: |
        flutter build apk --verbose
        ls -alh ./build/app/outputs/flutter-apk/*.apk
        cp -r ./build/app/outputs/flutter-apk /tmp/flutter-apk

    - name: Build Windows
      run: |
        flutter build windows --release
        ls -alh ./build/windows/runner/Release/*.exe
        cp -r ./build/windows/runner/Release /tmp/windows-exe

    - name: Upload Android
      uses: actions/upload-artifact@v4.3.3
      with:
        name: android-release
        path: /tmp/flutter-apk/*.apk
    
    - name: Upload Windows
      uses: actions/upload-artifact@v4.3.3
      with:
        name: windows-exe
        path: /tmp/windows-exe/*.exe